services:
  web:
    build: ./electronics_store
    image: web:1.0.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - static_volume:/usr/src/electronics_store/staticfiles
      - ./electronics_store:/usr/src/electronics_store
      - media_volume:/usr/src/electronics_store/media
    restart: unless-stopped # no, always, on-failure: 5
    env_file:
      - ./electronics_store/.env.dev
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres:17-bookworm
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - ./electronics_store/.env.dev
    networks:
      - dev

  dbbrowser:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - dev

  api:
    build: ./api
    image: api:1.0.0
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:9000:8000
    env_file:
      - ./api/.env.dev
    develop:
      watch:
        - action: sync
          path: ./api
          target: /usr/src/electronics_store
        - action: rebuild
          path: ./api/requirements.txt
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - dev

volumes:
  data:
  static_volume:
  static_api_volume:
  media_volume:

networks:
  dev: