services:
  web:
    build:
      context: ./electronics_store
      dockerfile: Dockerfile.prod
    image: web_prod:1.0.0
    command: gunicorn electronics_store.wsgi:application --bind 0.0.0.0:8000 --access-logfile '-'
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/electronics_store/static
      - media_volume:/usr/src/electronics_store/media
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=/run/secrets/pg_password
      - STRIPE_PUBLISHABLE_KEY=/run/secrets/stripe_publishable_key
      - STRIPE_SECRET_KEY=/run/secrets/stripe_secret_key
      - STRIPE_API_VERSION=${STRIPE_API_VERSION}
      - STRIPE_WEBHOOK_SECRET=/run/secrets/stripe_webhook_secret
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD==/run/secrets/email_host_password
    secrets:
      - pg_password
      - stripe_publishable_key
      - stripe_secret_key
      - stripe_webhook_secret
      - email_host_password
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:17-bookworm
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=/run/secrets/pg_password
    secrets:
      - pg_password
    networks:
      - app_net

  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
      - static_volume:/electronics_store/static
      - static_api_volume:/electronics_store/api-static
      - media_volume:/electronics_store/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - api
    networks:
      - app_net

  api:
    build: ./api
    image: api_prod:1.0.0
    command: gunicorn electronics_store.wsgi:application --bind 0.0.0.0:8001 --access-logfile '-'
    expose:
      - 8001
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - static_api_volume:/usr/src/electronics_store/static
      - media_volume:/usr/src/electronics_store/media
    secrets:
      - pg_password
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app_net

secrets:
  pg_password:
    file: ./sets/pg_secret_password.txt
  stripe_secret_key:
    file: ./sets/stripe_secret_key.txt
  stripe_publishable_key:
    file: ./sets/stripe_publishable_key.txt
  stripe_webhook_secret:
    file: ./sets/stripe_webhook_secret.txt
  email_host_password:
    file: ./sets/email_host_password.txt

volumes:
  data:
  static_volume:
  static_api_volume:
  media_volume:

networks:
  app_net:
