# Generated by Django 4.1.7 on 2025-02-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Бренд')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория товара')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name=' Количество')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brands', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.products', verbose_name='Продукт')),
                ('operating_system', models.CharField(blank=True, max_length=70, null=True, verbose_name='Операционная система')),
                ('type_operating_system', models.CharField(blank=True, max_length=70, null=True, verbose_name='Тип операционной системы')),
                ('processor', models.CharField(blank=True, max_length=70, null=True, verbose_name='Процессор')),
                ('processor_frequency', models.CharField(blank=True, max_length=70, null=True, verbose_name='Частота процессора')),
                ('number_of_cores', models.CharField(blank=True, max_length=70, null=True, verbose_name='Количество ядер')),
                ('screen_diagonal', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Диагональ экрана, дюймы')),
                ('display_features', models.PositiveIntegerField(blank=True, null=True, verbose_name='Особенности дисплея, Гц')),
                ('main_camera', models.PositiveIntegerField(blank=True, null=True, verbose_name='Основная камера, Мп')),
                ('front_camera', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фронтальная камера, Мп')),
                ('video_resolution', models.PositiveIntegerField(blank=True, null=True, verbose_name='Разрешение видео, К')),
                ('built_in_memory', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем встроенной памяти, ГБ')),
                ('random_access_memory', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем оперативной памяти, ГБ')),
                ('quantity_of_SIM', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество SIM карт')),
                ('sim_card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип SIM карты')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цвет изделия')),
                ('dimensions', models.CharField(blank=True, max_length=70, null=True, verbose_name='Габариты')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес, г')),
                ('battery_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Емкость аккумулятора, мАч')),
                ('bluetooth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bluetooth')),
                ('wi_fi', models.CharField(blank=True, max_length=70, null=True, verbose_name='Wi-Fi')),
                ('connection_connector', models.CharField(blank=True, max_length=50, null=True, verbose_name='Разъем подключения')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'characteristics',
            },
        ),
    ]
