# Generated by Django 4.1.7 on 2025-02-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='main_camera',
            field=models.CharField(blank=True, choices=[(8, 8), (12, 12), (32, 32), (48, 48), (50, 50), (64, 64), (100, 100), (108, 108), (200, 200)], max_length=50, null=True, verbose_name='Основная камера, Мп'),
        ),
    ]
