# Generated by Django 4.1.7 on 2025-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_characteristics_main_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='built_in_memory',
            field=models.CharField(blank=True, choices=[(64, 64), (128, 128), (256, 256), (512, 512), (1024, 1024)], max_length=10, null=True, verbose_name='Объем встроенной памяти, ГБ'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='main_camera',
            field=models.CharField(blank=True, choices=[(8, 8), (12, 12), (32, 32), (48, 48), (50, 50), (64, 64), (100, 100), (108, 108), (200, 200)], max_length=10, null=True, verbose_name='Основная камера, Мп'),
        ),
    ]
