# Generated by Django 4.1.7 on 2025-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_characteristics_built_in_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='random_access_memory',
            field=models.CharField(blank=True, choices=[(3, 3), (4, 4), (6, 6), (8, 8), (12, 12), (16, 16)], max_length=10, null=True, verbose_name='Объем оперативной памяти, ГБ'),
        ),
    ]
