# Generated by Django 4.1.7 on 2025-02-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_characteristics_built_in_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['id', 'slug'], name='products_id_b7370b_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
    ]
