# Generated by Django 4.1.7 on 2025-02-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
    ]
