# Generated by Django 4.1.7 on 2025-02-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
