# Generated by Django 4.2.19 on 2025-04-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_categories_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
    ]
