# Generated by Django 4.2.19 on 2025-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='main_camera',
            field=models.PositiveIntegerField(blank=True, choices=[(8, 8), (12, 12), (32, 32), (48, 48), (50, 50), (200, 200)], null=True, verbose_name='Основная камера, Мп'),
        ),
    ]
