# Апстримы — Django и API
upstream electronics_store {
  server web:8000;
}

upstream api {
  server api:8001;
}

# HTTP — редирект на HTTPS и доступ к Let's Encrypt challenge
server {
  listen 80;
  server_name electronics24.store www.electronics24.store;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

# HTTPS — основной сервер
server {
  listen 443 ssl;
  server_name electronics24.store www.electronics24.store;

  ssl_certificate /etc/letsencrypt/live/localhost/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  location / {
    proxy_pass http://electronics_store;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_redirect off;
  }

  location /api/ {
    proxy_pass http://api;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_redirect off;
  }

  location /static/ {
    alias /electronics_store/static/;
    add_header Cache-Control "public, no-transform";
  }

  location /media/ {
    alias /electronics_store/media/;
    add_header Cache-Control "public, no-transform";
  }

  location /api-static/ {
    alias /electronics_store/api-static/;
    add_header Cache-Control "public, no-transform";
  }

  location /api-media/ {
    alias /electronics_store/media/;
    add_header Cache-Control "public, no-transform";
  }
}
