name: Django CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create temporary env file
        run: |
          mkdir -p electronics_store
          cat <<EOF > electronics_store/.env.dev
          SECRET_KEY=test_secret_key_for_ci
          DJANGO_SETTINGS_MODULE=electronics_store.settings
          POSTGRES_HOST=db
          POSTGRES_PORT=5432
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=test_db
          EOF

      - name: Build Docker image
        run: docker compose -f compose.yml build web

      - name: Ensure logs folder volume
        run: |
          docker volume create logs_volume   

      - name: Start DB service
        run: docker compose -f compose.yml --env-file electronics_store/.env.dev up -d db

      - name: Debug entrypoint.sh inside container
        run: |
          echo "=== Проверка прав на entrypoint.sh ==="
          docker compose run --rm --entrypoint "" web ls -l /usr/src/electronics_store/entrypoint.sh
          echo "=== Проверка первых строк entrypoint.sh (символы переноса) ==="
          docker compose run --rm --entrypoint "" web head -n 5 /usr/src/electronics_store/entrypoint.sh | cat -A

      - name: Prepare logs folder
        run: |
          docker compose -f compose.yml --env-file electronics_store/.env.dev run --rm \
          -v logs_volume:/usr/src/electronics_store/logs web mkdir -p /usr/src/electronics_store/logs

      - name: Run migrations
        run: |
          docker compose -f compose.yml --env-file electronics_store/.env.dev run --rm  \
            -v logs_volume:/usr/src/electronics_store/logs web python manage.py migrate

      - name: Run tests with coverage
        run: |
         docker compose -f compose.yml --env-file electronics_store/.env.dev run --rm \
         -v logs_volume:/usr/src/electronics_store/logs \
         -v $(pwd)/electronics_store:/tmp_host \
         web pytest --ds=electronics_store.settings \
         --cov=/usr/src/electronics_store \
         --cov-config=/usr/src/electronics_store/.coveragerc \
         --cov-report=xml:/tmp_host/coverage.xml -o log_cli=true -o log_cli_level=INFO

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: electronics_store/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests

      - name: Show coverage.xml
        run: cat electronics_store/coverage.xml
